name: Deploy Azure Function App
on:
  push:
    branches: [ main ]
    paths:
      - backend/api/**
      - .github/workflows/function-deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build & Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: getresumecounterr
          package: backend/api
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
