name: Deploy static site to Azure Storage
on:
  push:
    branches: [ main ]
    paths:
      - frontend/** 
      - .github/workflows/storage-deploy.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Azure CLI
        uses: azure/cli@v2

      - name: Upload to $web container
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
          SOURCE_DIR: frontend
        run: |
          az storage blob upload-batch \
            --account-name "$AZURE_STORAGE_ACCOUNT" \
            --account-key "$AZURE_STORAGE_KEY" \
            -s "$SOURCE_DIR" \
            -d '$web' \
            --overwrite true

